[build]
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/.netlify/*"
  to = "/.netlify/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
